# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/UI/SiteWatcher.UI/" # Location of package manifests
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
