# fly.toml file generated for sitewatcherworker on 2022-11-19T16:55:33-03:00

app = "sitewatcherworker"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 3
    soft_limit = 2
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 8000

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = 300000
    grace_period = "10s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    restart_limit = 5
    timeout = "5s"
    tls_skip_verify = false
    [services.http_checks.headers]

[build]
  dockerfile = "src/Worker/Dockerfile"