// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Metadata;
using SiteWatcher.Domain.Models.Alerts.WatchModes;
using SiteWatcher.Infra.Persistence.Configuration;

#pragma warning disable 219, 612, 618
#nullable enable

namespace PersistenceCompiledModels
{
    internal partial class RegexWatchEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType? baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SiteWatcher.Domain.Models.Alerts.WatchModes.RegexWatch",
                typeof(RegexWatch),
                baseEntityType,
                discriminatorProperty: "WatchMode");

            var notifyOnDisappearance = runtimeEntityType.AddProperty(
                "NotifyOnDisappearance",
                typeof(bool),
                propertyInfo: typeof(RegexWatch).GetProperty("NotifyOnDisappearance", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RegexWatch).GetField("<NotifyOnDisappearance>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            notifyOnDisappearance.AddAnnotation("Relational:ColumnType", "boolean");

            var regexPattern = runtimeEntityType.AddProperty(
                "RegexPattern",
                typeof(string),
                propertyInfo: typeof(RegexWatch).GetProperty("RegexPattern", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RegexWatch).GetField("<RegexPattern>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            regexPattern.AddAnnotation("Relational:ColumnType", "varchar(512)");

            var _matches = runtimeEntityType.AddProperty(
                "_matches",
                typeof(List<string>),
                fieldInfo: typeof(RegexWatch).GetField("_matches", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new RegexWatchMatchesValueConverter());
            _matches.AddAnnotation("Relational:ColumnName", "Matches");
            _matches.AddAnnotation("Relational:ColumnType", "text");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("DiscriminatorValue", 'R');
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "siteWatcher_webApi");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "WatchModes");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
