// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SiteWatcher.Infra;

#pragma warning disable 219, 612, 618
#nullable enable

namespace PersistenceCompiledModels
{
    [DbContext(typeof(SiteWatcherContext))]
    public partial class SiteWatcherContextModel : RuntimeModel
    {
        static SiteWatcherContextModel()
        {
            var model = new SiteWatcherContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static SiteWatcherContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
