// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace PersistenceCompiledModels
{
    public partial class SiteWatcherContextModel
    {
        partial void Initialize()
        {
            var alert = AlertEntityType.Create(this);
            var site = SiteEntityType.Create(this);
            var termOccurrence = TermOccurrenceEntityType.Create(this);
            var watchMode = WatchModeEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var anyChangesWatch = AnyChangesWatchEntityType.Create(this, watchMode);
            var termWatch = TermWatchEntityType.Create(this, watchMode);

            AlertEntityType.CreateForeignKey1(alert, user);
            SiteEntityType.CreateForeignKey1(site, alert);
            TermOccurrenceEntityType.CreateForeignKey1(termOccurrence, termWatch);
            WatchModeEntityType.CreateForeignKey1(watchMode, alert);

            AlertEntityType.CreateAnnotations(alert);
            SiteEntityType.CreateAnnotations(site);
            TermOccurrenceEntityType.CreateAnnotations(termOccurrence);
            WatchModeEntityType.CreateAnnotations(watchMode);
            UserEntityType.CreateAnnotations(user);
            AnyChangesWatchEntityType.CreateAnnotations(anyChangesWatch);
            TermWatchEntityType.CreateAnnotations(termWatch);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.8");
            AddAnnotation("Relational:DefaultSchema", "siteWatcher_webApi");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
