// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace SiteWatcher.Infra.Persistence.CompiledModels
{
    public partial class SiteWatcherContextModel
    {
        partial void Initialize()
        {
            var alert = AlertEntityType.Create(this);
            var notification = NotificationEntityType.Create(this);
            var rule = RuleEntityType.Create(this);
            var termOccurrence = TermOccurrenceEntityType.Create(this);
            var site = SiteEntityType.Create(this);
            var idempotentConsumer = IdempotentConsumerEntityType.Create(this);
            var email = EmailEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var anyChangesRule = AnyChangesRuleEntityType.Create(this, rule);
            var regexRule = RegexRuleEntityType.Create(this, rule);
            var termRule = TermRuleEntityType.Create(this, rule);

            AlertEntityType.CreateForeignKey1(alert, user);
            NotificationEntityType.CreateForeignKey1(notification, alert);
            NotificationEntityType.CreateForeignKey2(notification, email);
            RuleEntityType.CreateForeignKey1(rule, alert);
            TermOccurrenceEntityType.CreateForeignKey1(termOccurrence, termRule);
            SiteEntityType.CreateForeignKey1(site, alert);
            EmailEntityType.CreateForeignKey1(email, user);

            AlertEntityType.CreateSkipNavigation1(alert, email, notification);
            EmailEntityType.CreateSkipNavigation1(email, alert, notification);

            AlertEntityType.CreateAnnotations(alert);
            NotificationEntityType.CreateAnnotations(notification);
            RuleEntityType.CreateAnnotations(rule);
            TermOccurrenceEntityType.CreateAnnotations(termOccurrence);
            SiteEntityType.CreateAnnotations(site);
            IdempotentConsumerEntityType.CreateAnnotations(idempotentConsumer);
            EmailEntityType.CreateAnnotations(email);
            UserEntityType.CreateAnnotations(user);
            AnyChangesRuleEntityType.CreateAnnotations(anyChangesRule);
            RegexRuleEntityType.CreateAnnotations(regexRule);
            TermRuleEntityType.CreateAnnotations(termRule);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.11");
            AddAnnotation("Relational:DefaultSchema", "sw");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
